// Mock Mobile Phone Dataset — simulates Kaggle 'sady36' dataset
// Hardware attributes: realistic ranges
// Subjective attributes: 1-10 scale

export const phones = [
  {
    id: 1,
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    image: "📱",
    // Hardware
    price: 129999,
    battery: 5000,
    screen: 6.8,
    storage: 512,
    processor: 3.39,
    camera: 200,
    charging: 45,
    // Subjective (1-10)
    performance: 10,
    quality: 9,
    sound: 8,
    design: 9,
    network: 10,
    software: 9,
    build: 10,
  },
  {
    id: 2,
    name: "Apple iPhone 16 Pro",
    brand: "Apple",
    image: "📱",
    price: 119900,
    battery: 3274,
    screen: 6.3,
    storage: 256,
    processor: 3.78,
    camera: 48,
    charging: 27,
    performance: 10,
    quality: 10,
    sound: 9,
    design: 10,
    network: 9,
    software: 10,
    build: 10,
  },
  {
    id: 3,
    name: "Google Pixel 9 Pro",
    brand: "Google",
    image: "📱",
    price: 109999,
    battery: 4700,
    screen: 6.3,
    storage: 256,
    processor: 3.1,
    camera: 50,
    charging: 37,
    performance: 9,
    quality: 9,
    sound: 8,
    design: 9,
    network: 9,
    software: 10,
    build: 9,
  },
  {
    id: 4,
    name: "OnePlus 12",
    brand: "OnePlus",
    image: "📱",
    price: 64999,
    battery: 5400,
    screen: 6.82,
    storage: 256,
    processor: 3.3,
    camera: 50,
    charging: 100,
    performance: 9,
    quality: 8,
    sound: 8,
    design: 8,
    network: 8,
    software: 8,
    build: 8,
  },
  {
    id: 5,
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    image: "📱",
    price: 99999,
    battery: 5000,
    screen: 6.73,
    storage: 512,
    processor: 3.3,
    camera: 50,
    charging: 90,
    performance: 9,
    quality: 9,
    sound: 8,
    design: 9,
    network: 9,
    software: 7,
    build: 9,
  },
  {
    id: 6,
    name: "Samsung Galaxy A55",
    brand: "Samsung",
    image: "📱",
    price: 38999,
    battery: 5000,
    screen: 6.6,
    storage: 128,
    processor: 2.75,
    camera: 50,
    charging: 25,
    performance: 7,
    quality: 7,
    sound: 6,
    design: 7,
    network: 7,
    software: 7,
    build: 7,
  },
  {
    id: 7,
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    image: "📱",
    price: 31999,
    battery: 4500,
    screen: 6.7,
    storage: 256,
    processor: 2.96,
    camera: 50,
    charging: 125,
    performance: 8,
    quality: 7,
    sound: 7,
    design: 8,
    network: 8,
    software: 8,
    build: 7,
  },
  {
    id: 8,
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    image: "📱",
    price: 18999,
    battery: 5000,
    screen: 6.7,
    storage: 128,
    processor: 2.85,
    camera: 50,
    charging: 45,
    performance: 7,
    quality: 7,
    sound: 6,
    design: 9,
    network: 7,
    software: 8,
    build: 8,
  },
  {
    id: 9,
    name: "ASUS ROG Phone 8 Pro",
    brand: "ASUS",
    image: "📱",
    price: 94999,
    battery: 5500,
    screen: 6.78,
    storage: 512,
    processor: 3.39,
    camera: 50,
    charging: 65,
    performance: 10,
    quality: 8,
    sound: 10,
    design: 7,
    network: 9,
    software: 8,
    build: 9,
  },
  {
    id: 10,
    name: "Realme 12 Pro+",
    brand: "Realme",
    image: "📱",
    price: 27999,
    battery: 5000,
    screen: 6.7,
    storage: 256,
    processor: 2.21,
    camera: 64,
    charging: 67,
    performance: 7,
    quality: 7,
    sound: 6,
    design: 8,
    network: 7,
    software: 6,
    build: 7,
  },
];

// Feature configuration: attribute keys + their realistic data ranges for normalization
export const FEATURE_CONFIG = {
  price:       { label: "Price",       unit: "₹",    min: 10000,  max: 140000, step: 1000 },
  battery:     { label: "Battery",     unit: "mAh",  min: 2000, max: 6000, step: 100 },
  screen:      { label: "Screen Size", unit: "in",   min: 5.0,  max: 7.2,  step: 0.1 },
  storage:     { label: "Storage",     unit: "GB",   min: 64,   max: 1024, step: 64  },
  processor:   { label: "Processor (GHz)", unit: "GHz",  min: 1.5,  max: 4.0,  step: 0.1 },
  camera:      { label: "Camera",      unit: "MP",   min: 12,   max: 200,  step: 2   },
  charging:    { label: "Charging",    unit: "W",    min: 15,   max: 150,  step: 5   },
  performance: { label: "Performance", unit: "/10",  min: 1,    max: 10,   step: 1   },
  quality:     { label: "Quality",     unit: "/10",  min: 1,    max: 10,   step: 1   },
  sound:       { label: "Sound",       unit: "/10",  min: 1,    max: 10,   step: 1   },
  design:      { label: "Design",      unit: "/10",  min: 1,    max: 10,   step: 1   },
  network:     { label: "Network",     unit: "/10",  min: 1,    max: 10,   step: 1   },
  software:    { label: "Software",    unit: "/10",  min: 1,    max: 10,   step: 1   },
  build:       { label: "Build",       unit: "/10",  min: 1,    max: 10,   step: 1   },
};

export const ALL_FEATURES = Object.keys(FEATURE_CONFIG);
